### ISSUE TITLE
Mujoco_py not compiling with Python 3.7 MacOS Catalina

### ISSUE THREAD

**Issue by rbharadwaj9** [ARISE-Initiative/robosuite#296]
It looks like there are compilation errors while building mujoco_py while trying to install robosuite in python3.7

### Steps followed: 
Installation guide from documentation. 
### Command failed: 
`CC=gcc-7 python -c "import robosuite"`
### Error Message:
```bash
$ gcc-7 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Header ...

gcc-7: error: unrecognized command line option '-iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders'
gcc-7: error: unrecognized command line option '-iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Headers'
```

### Some Analysis:
The package perfectly builds with Python 3.9. On comparing the compile commands, the flags are quite different although I'm not sure why.

Compile call on Python3.9
```
$ gcc-7 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -DONMAC ... (more arguments but not important)
```
Compile call on Python3.7
```
$ gcc-7 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Header -DONMAC (more arguments but not important)
```
I've tried recreating my virtual environment from scratch on both versions and the 3.9 one consistently builds fine.

**Comment by cremebrule** [comment]
Hi @rbharadwaj9 ,

Thanks for sharing details about your problem. I'm assuming this is on a non-M1 mac? Is there a reason why you aren't using gcc-9 to compile?

**Comment by rbharadwaj9** [comment]
Hi @cremebrule , 
This is on an Intel Macbook Pro 2018. I was following the tutorial from the documentation which hinted that `gcc-7` is required for compilation. I will try with `gcc-9` and follow-up.
